//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaInventory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckOutHistory
    {
        public int Id { get; set; }
        public int MOVid { get; set; }
        public int CSTid { get; set; }
        public System.DateTime CheckOutDate { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Movie Movie { get; set; }
    }
}
