//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaInventory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryUser
    {
        public int Id { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string CellPhone { get; set; }
        public int SQ1id { get; set; }
        public int SQ2id { get; set; }
        public int SQ3id { get; set; }
        public string Answer1 { get; set; }
        public string Answer2 { get; set; }
        public string Answer3 { get; set; }
        public int ROLid { get; set; }
    
        public virtual SecurityQuestion SecurityQuestion { get; set; }
        public virtual SecurityQuestion SecurityQuestion1 { get; set; }
        public virtual SecurityQuestion SecurityQuestion2 { get; set; }
        public virtual SecurityRole SecurityRole { get; set; }
    }
}
