//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaInventory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Movie()
        {
            this.CheckOutHistories = new HashSet<CheckOutHistory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int TMDbId { get; set; }
        public string IMDbId { get; set; }
        public bool IsOwned { get; set; }
        public bool IsWanted { get; set; }
        public int FORId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CheckOutHistory> CheckOutHistories { get; set; }
        public virtual Format Format { get; set; }
    }
}
