//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaInventory.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe2Ingredient2Measurement
    {
        public int Id { get; set; }
        public int INGid { get; set; }
        public int MEAid { get; set; }
        public int RECid { get; set; }
        public decimal Quantity { get; set; }
    
        public virtual Ingredient Ingredient { get; set; }
        public virtual Measurement Measurement { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
